### PR TITLE
Fix errors in rotation function in OSMPDummySensor

### LINKED ISSUE #94: Errors in rotation function in OSMPDummySensor
#### Describe the bug
In the rotatePoint() function of the OSMPDummySensor, a rotation matrix is calculated. Then the rotation matrix is multiplied by the relative translation of an object to the ego vehicle to get the relativ position considering the orientation of the ego.
However, since this is a transformation from a global coordinate system to a local coordinate system, it has to be the inverse (or transpose) of the rotation matrix multiplied by the translation. This is described in the [OSI documentation of the orientation field](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1Orientation3d.html):

image

Furthermore, when the rotatePoint() function is called in the doCalc() function, the orientation of the object is passed to the function instead of the ego orientation.

#### Describe how to reproduce the bug
Run a unit test on rotatePoint() and feed it e.g. a relative translation of (5,3,0) and a rotation of yaw = pi/2. This should result in a position of (3,-5,0). But instead it yields (-3,-5,0).
This example was run in a unit test in the OpenMSL template repo, which is based on the OSMPDummySensor. You can find the failed test result [here](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/actions/runs/4414328802/jobs/7735892106).

#### Describe the expected behavior
see example above

#### Describe the OS you are using
 - OS: Ubuntu 22.04
 - Language: C++
 - Version 1.3.0

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
#### Reference to a related issue in the repository
Fixes #94

#### Add a description
- Added a transpose function for the rotation matrix, as it is a transformation from a global coordinate system to a local system and therefore, the inverse needs to be used
- Changed using the objects orientation to using the ego orientation for calculating the relative position of an object with respect to the ego vehicle.

#### Check the checklist

- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation) for osi-sensor-model-packaging.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works: [Failed unit test](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/actions/runs/4414328802/jobs/7735892106), [Passing unit test](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/actions/runs/4414405272/jobs/7736070483)
- [x] New and existing unit tests / Github Actions pass locally with my changes.

### CODE REVIEW

**Review by PhRosenberger — COMMENTED** [review]
As this occured during unit testing and is now solved, it should be merged asap.

**Review by PhRosenberger — APPROVED** [review]

**Comment by thomassedlmayer** [comment]
Thanks for noticing/fixing the bug! The fix works with our tools.

Though, I thought we would maybe want to use the actual roll-pitch-yaw rotation matrix instead of using the yaw-pitch-roll matrix and then transpose? I made a proposal in my commit. What do you think?

I also added the transformation to vehicle coordinate system (center rear axle) and virtual sensor coordinate system as this was missing anyways. And I removed the rotatePoint function from the DummySource as this probably was a copy/paste mistake.

@ClemensLinnhoff Could you check if this works for you?

File: examples/OSMPDummySensor/OSMPDummySensor.cpp [hunk 1]
```diff
@@ -246,15 +258,60 @@ void rotatePoint(double x, double y, double z,double yaw,double pitch,double rol
...
+    double ego_bbcenter_to_rear_x, double ego_bbcenter_to_rear_y, double ego_bbcenter_to_rear_z)
+{
+    /* subtract global ego vehicle position from global coordinate */
+    rx = rx-ego_x;
+    ry = ry-ego_y;
+    rz = rz-ego_z;
+
+    /* rotate by negative ego vehicle orientation */
+    rotatePointXYZ(rx, ry, rz,
+        -ego_yaw, -ego_pitch, -ego_roll,
```
Comment (ClemensLinnhoff) [inline examples/OSMPDummySensor/OSMPDummySensor.cpp:281]: I think it is a bit unintuitive, that you have to call the function with negative angles.

File: examples/OSMPDummySensor/OSMPDummySensor.cpp [hunk 2]
```diff
@@ -246,15 +258,60 @@ void rotatePoint(double x, double y, double z,double yaw,double pitch,double rol
...
+    double mounting_position_yaw, double mounting_position_pitch, double mounting_position_roll)
+{
+    /* subtract virtual/physical sensor mounting position */
+    rx = rx-mounting_position_x;
+    ry = ry-mounting_position_y;
+    rz = rz-mounting_position_z;
+
+    /* rotate by negative virtual/physical sensor mounting orientation */
+    rotatePointXYZ(rx, ry, rz,
+        -mounting_position_yaw, -mounting_position_pitch, -mounting_position_roll,
```
Comment (ClemensLinnhoff) [inline examples/OSMPDummySensor/OSMPDummySensor.cpp:305]: Same as above

File: examples/OSMPDummySensor/OSMPDummySensor.cpp [hunk 3]
```diff
@@ -287,20 +350,27 @@ fmi2Status COSMPDummySensor::doCalc(fmi2Real currentCommunicationPoint, fmi2Real
...
                 if (veh.id().value() != ego_id.value()) {
-                    // NOTE: We currently do not take sensor mounting position into account,
-                    // i.e. sensor-relative coordinates are relative to center of bounding box
-                    // of ego vehicle currently.
-                    double trans_x = veh.base().position().x()-ego_x;
-                    double trans_y = veh.base().position().y()-ego_y;
-                    double trans_z = veh.base().position().z()-ego_z;
-                    double rel_x,rel_y,rel_z;
-                    rotatePoint(trans_x,trans_y,trans_z,veh.base().orientation().yaw(),veh.base().orientation().pitch(),veh.base().orientation().roll(),rel_x,rel_y,rel_z);
+                    double rel_x, rel_y, rel_z;
```
Comment (ClemensLinnhoff) [inline examples/OSMPDummySensor/OSMPDummySensor.cpp:355]: We can skip this, because the position is not realtive here anymore. I like, that you put the entire transformation into a separate function. So it can just directly be called with veh.base().position(). It would probably also be easier not to separate between x,y,z in the function call and just pass an osi::vector3d.

**Review by ClemensLinnhoff — COMMENTED** [review]
Apart from the individual comments in the code, I would acutally prefer to use the inverse of the rotation matrix instead of reversing the rotation order and the angles, because it would then be alligned with the mathematical definitions in the [documentation](https://opensimulationinterface.github.io/osi-documentation/#_coordinate_transformations).

File: examples/OSMPDummySensor/OSMPDummySensor.cpp (hunk 3 above)
Comment (ClemensLinnhoff) [reply examples/OSMPDummySensor/OSMPDummySensor.cpp:355]: After we talked I understand the approach not to use OSI types for internal functions. So this is fine with me.

**Comment by ClemensLinnhoff** [comment]
As I said above, for me it is easier to understand the coordinate transformtion by having only one rotation matrix and using the inverse depending on the transformation direction. But I can understand, that people might also find it easier doing it by reversing the rotation direction and the angle directions. So it would be fine for me to use your approach @thomassedlmayer 

I tested the current implementation with some unit tests and could not find an error, so the transformation (incl. translation and rotation) to vehicle and to the sensor seem to work.

File: examples/OSMPDummySensor/OSMPDummySensor.cpp [hunk 4]
```diff
@@ -236,7 +236,19 @@ fmi2Status COSMPDummySensor::doExitInitializationMode()
     return fmi2OK;
 }
 
-void rotatePoint(double x, double y, double z,double yaw,double pitch,double roll,double &rx,double &ry,double &rz)
+void transposeRotationMatrix(double matrix_in[3][3], double matrix_trans[3][3]) {
```
Comment (ClemensLinnhoff) [inline examples/OSMPDummySensor/OSMPDummySensor.cpp]: This function can be removed, as it is no longer needed.

**Comment by ClemensLinnhoff** [comment]
After removing the transpose function as noted above, the PR can be merged from my point of view.

**Comment by pmai** [comment]
CCB 2023-05-22: Merge as-is.
